name: Call Shared Workflow

on: 
  push:
  pull_request:

permissions: write-all

jobs:
  call-shared-workflow:
    uses: AdrienMS-Cap/tst-shared-pipeline/.github/workflows/create_workflow.yml@main
    with:
      repository: ${{ github.repository }}
      branch: ${{ github.event.ref }}

